### ISSUE TITLE
Grid not working in angular7

### ISSUE THREAD

**Issue by joecollett** [postcss/autoprefixer#1210]
I am trying to get Angular7 working nicely with the Autoprefixer. I'm specifically looking to get support on IE11. I've removed the "not" from "IE 9 - 11" in the browserlist file. I've also added

/* autoprefixer grid: autoplace / / autoprefixer grid: on */

To the top of my _grid.scss file. Problem is grid items are still not getting any prefixes. Flexbox seems to work fine but not CSS grid. Is there any configuration I've missed?

**Comment by Dan503** [comment]
It sounds like you have done everything right. The only thing a bit off in what you said is how you wrote the control comment. 

```css
/* autoprefixer grid: autoplace */
```

If you have included IE in your browsers list, and added that control comment, and you are using the latest version of Autoprefixer then it should be working for you.

**Comment by joecollett** [comment]
Tried that as well and its still not working 
![autoprefixer](https://user-images.githubusercontent.com/13499326/56819015-cdb68f80-6840-11e9-9b46-cb986baf2aad.PNG)
![browserlist](https://user-images.githubusercontent.com/13499326/56819027-d3ac7080-6840-11e9-8bf3-be9ef8dc9306.PNG)
![css](https://user-images.githubusercontent.com/13499326/56819032-d60eca80-6840-11e9-8cd3-ae9a097ffe2f.PNG)

**Comment by ai** [comment]
What is Autoprefixer version? You can check it by `npm ls | grep autoprefixer`.

**Comment by joecollett** [comment]
autoprefixer@9.5.1 extraneous

**Comment by ai** [comment]
Are you have only one Autoprefixer in that list?

**Comment by joecollett** [comment]
Found this error npm ERR! extraneous: autoprefixer@9.5.1 C:\Projects\ClientCommandCentre\node_modules\autoprefixer

**Comment by joecollett** [comment]
Yea only one on the list

**Comment by ai** [comment]
What is paths for Browserslist config and CSS file?

**Comment by joecollett** [comment]
C:\Projects\ClientCommandCentre\src\browserslist
C:\Projects\ClientCommandCentre\src\scss\base\_grid.scss

**Comment by ai** [comment]
Can you create a simple `scss/test.scss` with:

```scss
a {
  display: grid
}
```

Maybe the problem is in mixin?

**Comment by joecollett** [comment]
![simple](https://user-images.githubusercontent.com/13499326/56821718-035e7700-6847-11e9-9d4e-e38f4243dc93.PNG)
![test](https://user-images.githubusercontent.com/13499326/56821723-048fa400-6847-11e9-8e3a-7b5de6d4104d.PNG)

**Comment by joecollett** [comment]
Flexbox seems to work though 

![flexbox](https://user-images.githubusercontent.com/13499326/56821881-6cde8580-6847-11e9-8995-f64e18ceff47.PNG)
![flexbox2](https://user-images.githubusercontent.com/13499326/56821905-7a940b00-6847-11e9-928b-1161b5b896a0.PNG)

**Comment by Dan503** [comment]
Try this:

```css
/* autoprefixer grid: autoplace */
.test {
  display: grid;
  grid-template-rows: auto;
  grid-template-columns: auto;
}
```

**Comment by Dan503** [comment]
If that doesn't work, maybe your compiler is stripping out comments before Autoprefixer has a chance to run.

**Comment by joecollett** [comment]
So after the scss has been compiled the comments should still be in the css? Looks like the compiled style sheet doesnt have any of the comments.

**Comment by Dan503** [comment]
Yes. That is your problem.

Don't do this:

```scss
// autoprefixer grid: autoplace
.test {
  display: grid;
  grid-template-rows: auto;
  grid-template-columns: auto;
}
```

Do this:

```css
/* autoprefixer grid: autoplace */
.test {
  display: grid;
  grid-template-rows: auto;
  grid-template-columns: auto;
}
```

There is a difference.

**Comment by joecollett** [comment]
Yep thats what I'm doing, just when I'm building the application its optimizing the css so stripping out all the comments. Will give that ago and see if it works!

**Comment by Dan503** [comment]
You can also try this:
```css
/*! autoprefixer grid: autoplace */
.test {
  display: grid;
  grid-template-rows: auto;
  grid-template-columns: auto;
}
```

**Comment by joecollett** [comment]
Still not working
![comment](https://user-images.githubusercontent.com/13499326/56889892-b1e50080-6a6f-11e9-86a8-baa0f9d77daf.PNG)
![image](https://user-images.githubusercontent.com/13499326/56889924-c75a2a80-6a6f-11e9-875e-fb59e577382a.png)

**Comment by joecollett** [comment]
I've got it working, was some dependency issues ran npm audit fix and sorted the issue.

**Comment by Dan503** [comment]
Can you close the issue then?

**Comment by joecollett** [comment]
Thanks for your help

**Comment by SerkanSipahi** [comment]
@joecollett @Dan503 

I also try to activate the autoprefixer for the grid-layout (for flexboxes also not) on `angular cli v7.3.9` to generate prefxies but unfortunately it doesn't work:

I have an `browserlist` file in my `src` folder:
```
> 1% 
last 2 versions 
IE 11 
```
In top of my `styles.scss` which is located under `src` i add `/*! autoprefixer grid: on */`:
```
/*! autoprefixer grid: on */
@import '~normalize.css/normalize.css';
@import 'themes/saam-theme';
```

The css grid settings `grid-*` are located in the corresponding components e.g.
```
:host {
  @include grid-layout-homepage();
  @include grid-layout-result-page();
  @include grid-layout-detail-page();
}
```

What im doing wrong?

P.S. for flexboxes no prefixes are generated either

**Comment by ai** [comment]
@SerkanSipahi 

1. Run `npm ls | grep autoprefixer` and check all Autoprefixer versions.
2. Start from some simple example without SCSS and mixins. Just `index.css` with `/* autoprefixer grid: on */ body { display: grid }`

**Comment by SerkanSipahi** [comment]
@ai 
Now it works and I know what went wrong. By default, Angular has a project `src` folder with a styles.scss file in it. In this folder I set the autoprefixer directive in the head. I don't know what is happening under the hood (angular-cli) but apparently it has no effect to the angular component style files.  In order to create the prefixes you have to use the autoprefixer directive in every component where you use the grid syntax. 

The Angular cli generates a separate <style> tag for each component! Does anyone know how to apply an autoprefixer (`/* autoprefixer grid: on */`) directive globally to all componente style files?

**Comment by ai** [comment]
@SerkanSipahi you need access to PostCSS config to set option globally. As I know Angular doesn't provide this API.

**Comment by SerkanSipahi** [comment]
That's really very painful. Even for flexboxes you have to set the autoprefixer directive for flexbox in each angular component. We use encapsulated components (we have no global styling file). I don't know if you can solve the problem in our situation with encapsulated components. 

@ai 
I had read somewhere that you can drag the webpack configuration over the angular-cli. I guess I'll have to find out.

**Comment by antonsamper** [comment]
Both `/* autoprefixer grid: on */` and `/* autoprefixer grid: autoplace */` are working but i've had to add them to each individual SCSS file

**Comment by adamdport** [comment]
I ran into the same issue, solely because [the angular docs tell us to put it at the top of the global styles file](https://angular.io/guide/build#backward-compatibility-with-css-grid). It didn't work for me in my project, but when I tried to reproduce it in a new project, it worked fine. Not sure what causes it to stop working.

**Comment by Dan503** [comment]
That's weird, the documentation says to use:

```
/* autoprefixer grid: autoplace /
```
or
```
/ autoprefixer grid: no-autoplace */
```

It is meant to be this:

```
/* autoprefixer grid: no-autoplace */
```
Unless if the Angular examples are Angular's way of telling it not to remove the comments when compiling.

**Comment by dyingangel666** [comment]
Autoprefixer doesn't check your scss code, he's checking the already compiled css code. So you have to mention where to add your autoprefixer comments. And as far as i know, the autoprefixer comments are just used for the whole next css block.
